# Generated by Django 3.0.2 on 2020-01-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20200110_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='illustrations',
            field=models.CharField(blank=True, max_length=600, verbose_name='插图'),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.BooleanField(default=False, verbose_name='博客状态'),
        ),
    ]
